# Generated by Django 4.1.6 on 2023-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_url', models.CharField(max_length=300)),
                ('output_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
